name: Generate changeset to dependencies updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  changeset-pr:
    name: Add changeset to dependencies PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-update-dependencies')

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@v1.0.5
        with:
          use-conventional-commits: true
