name: Auto update dependencies PR

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  changeset-pr:
    name: Add changeset
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-update-dependencies')

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@v1.2.2
        with:
          use-conventional-commits: true
          author-name: "Changesets GH Action"
          author-email: "github-actions[bot]@users.noreply.github.com"
          token: ${{ secrets.DEPS_BUMP_ADD_CHANGESET_ACTION_PAT }}
